import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'ml';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    dashboard: 'Dashboard',
    documents: 'Documents',
    upload: 'Upload',
    search: 'Search',
    alerts: 'Alerts',
    auditLogs: 'Audit Logs',
    analytics: 'Analytics',
    settings: 'Settings',
    engineering: 'Engineering',
    finance: 'Finance',
    hr: 'Human Resources',
    safety: 'Safety',
    legal: 'Legal',
    operations: 'Operations',
    connectors: 'System Connectors',
    departments: 'Departments',
    fetchEmail: 'Fetch from Email',
    processing: 'Processing...',
    fetchingDocument: 'Fetching document from email...',
    documentFetched: 'Document fetched successfully',
    auctionNotice: 'Public Auction Notice - KMRL Movable Property',
    welcomeKmrl: 'Welcome to KMRL Document Processing System',
    kmrlFullName: 'Kochi Metro Rail Limited',
    kmrlDocuMindDashboard: 'KMRL DocuMind Dashboard',
    intelligentDocProcessing: 'Intelligent Document Processing System',
    recentActivity: 'Recent Activity',
    quickActions: 'Quick Actions',
    uploadDocument: 'Upload Document',
    searchFiles: 'Search Files',
    viewAlerts: 'View Alerts',
    generateReport: 'Generate Report',
    documentReceivedEmail: 'Document Received via Email',
    kmrlAuctionNoticeReceived: 'KMRL Auction Notice received in email system',
    retrievingFromEmailServer: 'Retrieving document from email server...',
    auctionNoticeProcessed: 'KMRL Auction Notice has been processed and is ready',
    auctionNoticeReady: 'Auction Notice ready for AI analysis',
    aiProcessingComplete: 'AI Processing Complete',
    documentReadyForQueries: 'Document is now ready for intelligent queries',
    newDocumentReceived: 'New Document Received',
    // Metric translations
    totalDocuments: 'Total Documents',
    criticalAlerts: 'Critical Alerts',
    departmentsActive: 'Departments Active',
    docs: 'docs',
    active: 'active',
    depts: 'depts',
    thisWeek: 'this week',
    // Activity translations
    trackMaintenanceUpdated: 'Track Maintenance Schedule Updated',
    maintenanceScheduleDesc: 'Q4 2024 maintenance schedule has been uploaded with critical updates',
    safetyNoticePublished: 'Safety Notice Published',
    safetyGuidelinesDesc: 'New platform safety guidelines available in Malayalam',
    invoiceProcessingComplete: 'Invoice Processing Complete',
    siemensPaymentDesc: 'Siemens vendor payment has been processed successfully',
    complianceReviewRequired: 'Compliance Review Required',
    cmrsReportDesc: 'CMRS report requires immediate attention',
    hoursAgo: 'hours ago',
    // Connector translations
    connected: 'Connected',
    disconnected: 'Disconnected',
    syncing: 'Syncing',
    lastSync: 'Last sync',
    minutesAgo: 'minutes ago',
    syncingNow: 'Syncing now...',
    kmrlEmailSystem: 'KMRL Email System',
    metroDatabase: 'Metro Database',
    documentCloud: 'Document Cloud',
    vendorPortalApi: 'Vendor Portal API',
    emailIntegrationDesc: 'Official KMRL email integration for document reception',
    databaseConnectionDesc: 'Main operational database connection',
    cloudSyncDesc: 'Cloud storage synchronization',
    vendorApiDesc: 'External vendor document API',
    manageAll: 'Manage All',
    // Upload page translations
    uploadDocuments: 'Upload Documents',
    uploadToDocuMind: 'Upload new documents to the DocuMind AI processing system',
    uploadGuidelines: 'Upload Guidelines',
    supportedFileTypes: 'Supported File Types',
    pdfDocuments: 'PDF Documents (.pdf)',
    msWord: 'Microsoft Word (.doc, .docx)',
    msExcel: 'Microsoft Excel (.xls, .xlsx)',
    images: 'Images (.png, .jpg, .jpeg, .gif)',
    bestPractices: 'Best Practices',
    descriptiveFileNames: 'Use descriptive file names',
    maxFileSize: 'Maximum file size: 20MB',
    readableDocuments: 'Ensure documents are readable',
    relevantMetadata: 'Include relevant metadata',
    aiPoweredUpload: 'AI-Powered Document Upload',
    dragDropFiles: 'Drag and drop your files here, or click to browse',
    supportsFileTypes: 'Supports PDF, Word, Excel, and Images (Max 20MB per file)',
    automaticAISummarization: 'Automatic AI summarization and metadata extraction',
    browseFiles: 'Browse Files',
    uploadedFiles: 'Uploaded Files',
    processingInfo: 'Processing Information',
    aiProcessingDesc: 'Once uploaded, your documents will be automatically processed by our AI system to:',
    extractKeyInfo: 'Extract key information and metadata',
    classifyDocType: 'Classify document type and department',
    identifyUrgency: 'Identify urgency level and priority',
    generateSummaries: 'Generate searchable summaries',
    multilingualProcessing: 'Apply multilingual processing (English/Malayalam)',
    processingTime: 'Processing typically takes 1-3 minutes depending on document size and complexity.',
    // Documents page translations
    manageSearchDocuments: 'Manage and search through all your documents',
    showingResults: 'Showing',
    ofDocuments: 'of',
    documentsText: 'documents',
    clearAllFilters: 'Clear all filters',
    noDocumentsFound: 'No documents found',
    adjustSearchTerms: 'Try adjusting your search terms or filters',
    latestFirst: 'Latest First',
    titleAZ: 'Title A-Z',
    urgency: 'Urgency',
    documentType: 'Document Type',
    // Auction document specific Q&A
    auctionQuestions: [
      'What is the reserve price for the KMRL auction?',
      'When is the auction date and time?',
      'What items are included in the auction?',
      'Where can I inspect the items before auction?',
      'What is the earnest money deposit amount?',
      'What are the terms and conditions for bidding?'
    ],
    auctionAnswers: [
      'The reserve price for the KMRL movable property auction is Rs. 25,000/- (Rupees Twenty five thousand only).',
      'The auction is scheduled for 14/03/2024 at 11:30 AM at JLN Stadium Metro Station.',
      'The auction includes various items like kiosk structure, electronic equipment, kitchen items, and 143 glass bottles of soda/juice among others.',
      'Item inspection can be done on 07-03-2024 & 11-03-2024 between 10:30 AM and 5:30 PM with prior permission from Estate Officer (0484-2846721).',
      'The earnest money deposit (EMD) required is Rs. 5,000/- (Rupees Five Thousand Only).',
      'The auction is conducted on "as is where is" basis without recourse. Bidders must inspect items beforehand and cannot raise objections later.'
    ],
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    documents: 'दस्तावेज़',
    upload: 'अपलोड',
    search: 'खोज',
    alerts: 'अलर्ट',
    auditLogs: 'ऑडिट लॉग्स',
    analytics: 'एनालिटिक्स',
    settings: 'सेटिंग्स',
    engineering: 'इंजीनियरिंग',
    finance: 'वित्त',
    hr: 'मानव संसाधन',
    safety: 'सुरक्षा',
    legal: 'कानूनी',
    operations: 'संचालन',
    connectors: 'सिस्टम कनेक्टर्स',
    departments: 'विभाग',
    fetchEmail: 'ईमेल से प्राप्त करें',
    processing: 'प्रोसेसिंग...',
    fetchingDocument: 'ईमेल से दस्तावेज़ प्राप्त कर रहे हैं...',
    documentFetched: 'दस्तावेज़ सफलतापूर्वक प्राप्त हुआ',
    auctionNotice: 'सार्वजनिक नीलामी सूचना - KMRL चल संपत्ति',
    welcomeKmrl: 'KMRL दस्तावेज़ प्रसंस्करण प्रणाली में आपका स्वागत है',
    kmrlFullName: 'कोच्चि मेट्रो रेल लिमिटेड',
    kmrlDocuMindDashboard: 'KMRL DocuMind डैशबोर्ड',
    intelligentDocProcessing: 'बुद्धिमान दस्तावेज़ प्रसंस्करण प्रणाली',
    recentActivity: 'हाल की गतिविधि',
    quickActions: 'त्वरित क्रियाएं',
    uploadDocument: 'दस्तावेज़ अपलोड करें',
    searchFiles: 'फ़ाइलें खोजें',
    viewAlerts: 'अलर्ट देखें',
    generateReport: 'रिपोर्ट जेनरेट करें',
    documentReceivedEmail: 'ईमेल के माध्यम से दस्तावेज़ प्राप्त हुआ',
    kmrlAuctionNoticeReceived: 'KMRL नीलामी सूचना ईमेल सिस्टम में प्राप्त हुई',
    retrievingFromEmailServer: 'ईमेल सर्वर से दस्तावेज़ प्राप्त कर रहे हैं...',
    auctionNoticeProcessed: 'KMRL नीलामी सूचना प्रोसेस हो गई है और तैयार है',
    auctionNoticeReady: 'नीलामी सूचना AI विश्लेषण के लिए तैयार',
    aiProcessingComplete: 'AI प्रसंस्करण पूर्ण',
    documentReadyForQueries: 'दस्तावेज़ अब बुद्धिमान प्रश्नों के लिए तैयार है',
    newDocumentReceived: 'नया दस्तावेज़ प्राप्त हुआ',
    // Metric translations
    totalDocuments: 'कुल दस्तावेज़',
    criticalAlerts: 'महत्वपूर्ण अलर्ट',
    departmentsActive: 'सक्रिय विभाग',
    docs: 'डॉक्स',
    active: 'सक्रिय',
    depts: 'विभाग',
    thisWeek: 'इस सप्ताह',
    // Activity translations
    trackMaintenanceUpdated: 'ट्रैक रखरखाव अनुसूची अपडेट',
    maintenanceScheduleDesc: 'Q4 2024 रखरखाव अनुसूची महत्वपूर्ण अपडेट के साथ अपलोड की गई',
    safetyNoticePublished: 'सुरक्षा सूचना प्रकाशित',
    safetyGuidelinesDesc: 'मलयालम में नई प्लेटफॉर्म सुरक्षा दिशानिर्देश उपलब्ध',
    invoiceProcessingComplete: 'चालान प्रसंस्करण पूर्ण',
    siemensPaymentDesc: 'सीमेंस विक्रेता भुगतान सफलतापूर्वक प्रसंस्करित',
    complianceReviewRequired: 'अनुपालन समीक्षा आवश्यक',
    cmrsReportDesc: 'CMRS रिपोर्ट को तत्काल ध्यान की आवश्यकता',
    hoursAgo: 'घंटे पहले',
    // Role selector
    viewAs: 'के रूप में देखें',
    overallSystemOverview: 'समग्र सिस्टम अवलोकन',
    // Connector translations
    connected: 'कनेक्ट किया गया',
    disconnected: 'डिस्कनेक्ट किया गया',
    syncing: 'सिंक हो रहा है',
    lastSync: 'अंतिम सिंक',
    minutesAgo: 'मिनट पहले',
    syncingNow: 'अब सिंक हो रहा है...',
    kmrlEmailSystem: 'KMRL ईमेल सिस्टम',
    metroDatabase: 'मेट्रो डेटाबेस',
    documentCloud: 'दस्तावेज़ क्लाउड',
    vendorPortalApi: 'विक्रेता पोर्टल API',
    emailIntegrationDesc: 'दस्तावेज़ रिसेप्शन के लिए आधिकारिक KMRL ईमेल इंटीग्रेशन',
    databaseConnectionDesc: 'मुख्य परिचालन डेटाबेस कनेक्शन',
    cloudSyncDesc: 'क्लाउड स्टोरेज सिंक्रोनाइज़ेशन',
    vendorApiDesc: 'बाहरी विक्रेता दस्तावेज़ API',
    manageAll: 'सभी प्रबंधित करें',
    // Upload page translations
    uploadDocuments: 'दस्तावेज़ अपलोड करें',
    uploadToDocuMind: 'DocuMind AI प्रसंस्करण प्रणाली में नए दस्तावेज़ अपलोड करें',
    uploadGuidelines: 'अपलोड दिशानिर्देश',
    supportedFileTypes: 'समर्थित फ़ाइल प्रकार',
    pdfDocuments: 'PDF दस्तावेज़ (.pdf)',
    msWord: 'Microsoft Word (.doc, .docx)',
    msExcel: 'Microsoft Excel (.xls, .xlsx)',
    images: 'छवियां (.png, .jpg, .jpeg, .gif)',
    bestPractices: 'सर्वोत्तम प्रथाएं',
    descriptiveFileNames: 'वर्णनात्मक फ़ाइल नाम का उपयोग करें',
    maxFileSize: 'अधिकतम फ़ाइल आकार: 20MB',
    readableDocuments: 'सुनिश्चित करें कि दस्तावेज़ पढ़ने योग्य हैं',
    relevantMetadata: 'प्रासंगिक मेटाडेटा शामिल करें',
    aiPoweredUpload: 'AI-संचालित दस्तावेज़ अपलोड',
    dragDropFiles: 'अपनी फ़ाइलों को यहाँ खींचें और छोड़ें, या ब्राउज़ करने के लिए क्लिक करें',
    supportsFileTypes: 'PDF, Word, Excel, और Images का समर्थन करता है (अधिकतम 20MB प्रति फ़ाइल)',
    automaticAISummarization: 'स्वचालित AI सारांश और मेटाडेटा निकासी',
    browseFiles: 'फ़ाइलें ब्राउज़ करें',
    uploadedFiles: 'अपलोड की गई फ़ाइलें',
    processingInfo: 'प्रसंस्करण जानकारी',
    aiProcessingDesc: 'अपलोड होने के बाद, आपके दस्तावेज़ स्वचालित रूप से हमारे AI सिस्टम द्वारा प्रसंस्करित होंगे:',
    extractKeyInfo: 'मुख्य जानकारी और मेटाडेटा निकालें',
    classifyDocType: 'दस्तावेज़ प्रकार और विभाग को वर्गीकृत करें',
    identifyUrgency: 'तात्कालिकता स्तर और प्राथमिकता की पहचान करें',
    generateSummaries: 'खोजने योग्य सारांश उत्पन्न करें',
    multilingualProcessing: 'बहुभाषी प्रसंस्करण लागू करें (अंग्रेजी/मलयालम)',
    processingTime: 'दस्तावेज़ के आकार और जटिलता के आधार पर प्रसंस्करण में आमतौर पर 1-3 मिनट लगते हैं।',
    // Documents page translations
    manageSearchDocuments: 'अपने सभी दस्तावेज़ों का प्रबंधन और खोज करें',
    showingResults: 'दिखा रहे हैं',
    ofDocuments: 'में से',
    documentsText: 'दस्तावेज़',
    clearAllFilters: 'सभी फ़िल्टर साफ़ करें',
    noDocumentsFound: 'कोई दस्तावेज़ नहीं मिला',
    adjustSearchTerms: 'अपने खोज शब्दों या फ़िल्टर को समायोजित करने का प्रयास करें',
    latestFirst: 'नवीनतम पहले',
    titleAZ: 'शीर्षक A-Z',
    urgency: 'तात्कालिकता',
    documentType: 'दस्तावेज़ प्रकार',
    // Auction document specific Q&A
    auctionQuestions: [
      'KMRL नीलामी की आरक्षित कीमत क्या है?',
      'नीलामी की तारीख और समय कब है?',
      'नीलामी में कौन से आइटम शामिल हैं?',
      'नीलामी से पहले मैं वस्तुओं का निरीक्षण कहाँ कर सकता हूं?',
      'बयाना राशि जमा की राशि क्या है?',
      'बोली लगाने के नियम और शर्तें क्या हैं?'
    ],
    auctionAnswers: [
      'KMRL चल संपत्ति नीलामी की आरक्षित कीमत रु. 25,000/- (रुपये पच्चीस हजार मात्र) है।',
      'नीलामी 14/03/2024 को सुबह 11:30 बजे JLN स्टेडियम मेट्रो स्टेशन पर निर्धारित है।',
      'नीलामी में कियोस्क संरचना, इलेक्ट्रॉनिक उपकरण, रसोई की वस्तुएं, और अन्य वस्तुओं के साथ 143 सोडा/जूस के कांच की बोतलें शामिल हैं।',
      'वस्तुओं का निरीक्षण 07-03-2024 और 11-03-2024 को सुबह 10:30 से शाम 5:30 के बीच एस्टेट ऑफिसर (0484-2846721) की पूर्व अनुमति से किया जा सकता है।',
      'आवश्यक बयाना राशि जमा (EMD) रु. 5,000/- (रुपये पांच हजार मात्र) है।',
      'नीलामी "जैसी है जहाँ है" के आधार पर बिना किसी सहारे के आयोजित की जाती है। बोलीदाताओं को पहले से वस्तुओं का निरीक्षण करना होगा और बाद में आपत्ति नहीं उठा सकते।'
    ],
  },
  ml: {
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    documents: 'രേഖകൾ',
    upload: 'അപ്‌ലോഡ്',
    search: 'തിരയുക',
    alerts: 'അലേർട്ടുകൾ',
    auditLogs: 'ഓഡിറ്റ് ലോഗുകൾ',
    analytics: 'അനാലിറ്റിക്സ്',
    settings: 'ക്രമീകരണങ്ങൾ',
    engineering: 'എഞ്ചിനീയറിംഗ്',
    finance: 'ധനകാര്യം',
    hr: 'മനുഷ്യവിഭവശേഷി',
    safety: 'സുരക്ഷ',
    legal: 'നിയമപരമായ',
    operations: 'പ്രവർത്തനങ്ങൾ',
    connectors: 'സിസ്റ്റം കണക്ടറുകൾ',
    departments: 'വകുപ്പുകൾ',
    fetchEmail: 'ഇമെയിലിൽ നിന്നും എടുക്കുക',
    processing: 'പ്രോസസ്സിംഗ്...',
    fetchingDocument: 'ഇമെയിലിൽ നിന്നും രേഖ എടുക്കുന്നു...',
    documentFetched: 'രേഖ വിജയകരമായി എടുത്തു',
    auctionNotice: 'പൊതു ലേലം അറിയിപ്പ് - KMRL ചരക്ക് സ്വത്ത്',
    welcomeKmrl: 'KMRL രേഖ പ്രോസസ്സിംഗ് സിസ്റ്റത്തിലേക്ക് സ്വാഗതം',
    kmrlFullName: 'കൊച്ചി മെട്രോ റെയിൽ ലിമിറ്റഡ്',
    kmrlDocuMindDashboard: 'KMRL DocuMind ഡാഷ്‌ബോർഡ്',
    intelligentDocProcessing: 'ബുദ്ധിമുട്ടുള്ള രേഖ പ്രോസസ്സിംഗ് സിസ്റ്റം',
    recentActivity: 'സമീപകാല പ്രവർത്തനം',
    quickActions: 'വേഗത്തിലുള്ള പ്രവർത്തനങ്ങൾ',
    uploadDocument: 'രേഖ അപ്‌ലോഡ് ചെയ്യുക',
    searchFiles: 'ഫയലുകൾ തിരയുക',
    viewAlerts: 'അലേർട്ടുകൾ കാണുക',
    generateReport: 'റിപ്പോർട്ട് ജനറേറ്റ് ചെയ്യുക',
    documentReceivedEmail: 'ഇമെയിൽ വഴി രേഖ ലഭിച്ചു',
    kmrlAuctionNoticeReceived: 'KMRL ലേലം അറിയിപ്പ് ഇമെയിൽ സിസ്റ്റത്തിൽ ലഭിച്ചു',
    retrievingFromEmailServer: 'ഇമെയിൽ സെർവറിൽ നിന്ന് രേഖ എടുക്കുന്നു...',
    auctionNoticeProcessed: 'KMRL ലേലം അറിയിപ്പ് പ്രോസസ്സ് ചെയ്യപ്പെട്ടു, തയ്യാറാണ്',
    auctionNoticeReady: 'ലേലം അറിയിപ്പ് AI വിശകലനത്തിനായി തയ്യാറ്',
    aiProcessingComplete: 'AI പ്രോസസ്സിംഗ് പൂർത്തിയായി',
    documentReadyForQueries: 'രേഖ ഇപ്പോൾ ബുദ്ധിമാനായ ചോദ്യങ്ങൾക്കായി തയ്യാറാണ്',
    newDocumentReceived: 'പുതിയ രേഖ ലഭിച്ചു',
    // Metric translations
    totalDocuments: 'മൊത്തം രേഖകൾ',
    criticalAlerts: 'ക്രിട്ടിക്കൽ അലേർട്ടുകൾ',
    departmentsActive: 'സജീവ വകുപ്പുകൾ',
    docs: 'ഡോക്സ്',
    active: 'സജീവം',
    depts: 'വകുപ്പുകൾ',
    thisWeek: 'ഈ ആഴ്‌ച',
    // Activity translations
    trackMaintenanceUpdated: 'ട്രാക്ക് പരിപാലന ഷെഡ്യൂൾ അപ്‌ഡേറ്റ്',
    maintenanceScheduleDesc: 'Q4 2024 പരിപാലന ഷെഡ്യൂൾ നിർണായക അപ്‌ഡേറ്റുകളോടെ അപ്‌ലോഡ് ചെയ്തു',
    safetyNoticePublished: 'സുരക്ഷാ അറിയിപ്പ് പ്രസിദ്ധീകരിച്ചു',
    safetyGuidelinesDesc: 'മലയാളത്തിൽ പുതിയ പ്ലാറ്റ്‌ഫോം സുരക്ഷാ മാർഗ്ഗനിർദ്ദേശങ്ങൾ ലഭ്യം',
    invoiceProcessingComplete: 'ഇൻവോയ്‌സ് പ്രോസസ്സിംഗ് പൂർത്തിയായി',
    siemensPaymentDesc: 'സീമൻസ് വെണ്ടർ പേയ്‌മെന്റ് വിജയകരമായി പ്രോസസ്സ് ചെയ്തു',
    complianceReviewRequired: 'കംപ്ലയൻസ് റിവ്യൂ ആവശ്യം',
    cmrsReportDesc: 'CMRS റിപ്പോർട്ടിന് അടിയന്തര ശ്രദ്ധ ആവശ്യം',
    hoursAgo: 'മണിക്കൂർ മുമ്പ്',
    // Role selector
    viewAs: 'ആയി കാണുക',
    overallSystemOverview: 'മൊത്തത്തിലുള്ള സിസ്റ്റം അവലോകനം',
    // Connector translations
    connected: 'കണക്റ്റഡ്',
    disconnected: 'ഡിസ്കണക്റ്റഡ്',
    syncing: 'സിങ്ക് ചെയ്യുന്നു',
    lastSync: 'അവസാന സിങ്ക്',
    minutesAgo: 'മിനിറ്റ് മുമ്പ്',
    syncingNow: 'ഇപ്പോൾ സിങ്ക് ചെയ്യുന്നു...',
    kmrlEmailSystem: 'KMRL ഇമെയിൽ സിസ്റ്റം',
    metroDatabase: 'മെട്രോ ഡേറ്റാബേസ്',
    documentCloud: 'ഡോക്യുമെന്റ് ക്ലൗഡ്',
    vendorPortalApi: 'വെണ്ടർ പോർട്ടൽ API',
    emailIntegrationDesc: 'ഡോക്യുമെന്റ് റിസപ്ഷനായി ഔദ്യോഗിക KMRL ഇമെയിൽ ഇന്റഗ്രേഷൻ',
    databaseConnectionDesc: 'പ്രധാന പ്രവർത്തന ഡേറ്റാബേസ് കണക്ഷൻ',
    cloudSyncDesc: 'ക്ലൗഡ് സ്റ്റോറേജ് സിൻക്രൊണൈസേഷൻ',
    vendorApiDesc: 'ബാഹ്യ വെണ്ടർ ഡോക്യുമെന്റ് API',
    manageAll: 'എല്ലാം കൈകാര്യം ചെയ്യുക',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}